from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 217)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 391, 179))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushHRS = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.pushHRS.setFont(font)
        self.pushHRS.setObjectName("pushHRS")
        self.horizontalLayout.addWidget(self.pushHRS)
        self.pushMIN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.pushMIN.setFont(font)
        self.pushMIN.setObjectName("pushMIN")
        self.horizontalLayout.addWidget(self.pushMIN)
        self.pushALARM = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.pushALARM.setFont(font)
        self.pushALARM.setObjectName("pushALARM")
        self.horizontalLayout.addWidget(self.pushALARM)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.text.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.horizontalLayout_2.addWidget(self.text)
        self.AlarmTime = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AlarmTime.sizePolicy().hasHeightForWidth())
        self.AlarmTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.AlarmTime.setFont(font)
        self.AlarmTime.setAutoFillBackground(False)
        self.AlarmTime.setObjectName("AlarmTime")
        self.horizontalLayout_2.addWidget(self.AlarmTime)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushHRS.setText(_translate("Dialog", "H"))
        self.pushMIN.setText(_translate("Dialog", "M"))
        self.pushALARM.setText(_translate("Dialog", "A"))
        self.text.setPlaceholderText(_translate("Dialog", "00:00"))
        self.AlarmTime.setPlaceholderText(_translate("Dialog", "00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
